### ISSUE TITLE
Url rewriting in to index.html

### ISSUE THREAD

**Issue by guehmann** [JuergenGutsch/angular2-aspnetcore-vs#3]
Hi,

I'm using your code in the Configure method (middleware) for rewriting index.html to avoid the refresh problem with 404. This works fine for simple routes without a parameter.

If i specifiy for example: http://localhost/myApp/base-department-detail/3 i get the 404 on
http://localhost/myApp/base-department-detail/styles.bundle.js and for some other .js also.

The '3' is the id of my department i want to show with another angular component.

Perhaps you see if i'm missing something.
Thanks in advance.
Regards Jens

**Comment by JuergenGutsch** [comment]
Hi Jens,
you are running that web in a sub web (myApp) of http://localhost/, right?
The redirection expects the index.html on http://localhost/index.html which is wrong in that case.
You need to arrange the redirect to match the sub web.

An ugly quick fix: `context.Request.Path = "/myApp/index.html";`

**Comment by guehmann** [comment]
Hi Juergen,

thanks for reply. Sorry for missing details. Yes my application runs as a virtual application under IIS.
Thanks for your solution.
Regards Jens.
